### FOREST

### Test Forests
GET http://localhost:3000/forests
Content-Type: application/json

### Test forestsById
GET http://localhost:3000/forests/1
Content-Type: application/json

### Test addForest
POST http://localhost:3000/forests
Content-Type: application/json

{
    "name": "Zones de Reforestation de la République Dominicaine",
    "association": "GreenRoots",
    "image": "imageforet8.jpg",
    "description": "Pays ayant subi une déforestation sévère avec un besoin urgent de reforestation.",
    "country": "République Dominicaine",
    "locationX": 19.000000,
    "locationY": -72.000000
}

### Test updateForest
PATCH http://localhost:3000/forests/1
Content-Type: application/json

{
  "country": "Brésil"
}

### Test deleteForest
DELETE http://localhost:3000/forests/7
Content-Type: application/json

### TREES

### Test Trees
GET http://localhost:3000/trees
Content-Type: application/json

### Test treeById
GET http://localhost:3000/trees/1
Content-Type: application/json

### Test addTree
POST http://localhost:3000/trees
Content-Type: application/json

{
    "name": "Palmier du Bengale",
    "scientific_name": "Plumeria rubra",
    "image": "palmier_bengale.jpg",
    "category": "Feuillu",
    "description": "Super arbre",
    "co2": 23,
    "o2": 46,
    "price": 50
}

### Test updateTree
PATCH http://localhost:3000/trees/11
Content-Type: application/json

{
  "category": "Conifère"
}

### Test deleteTree
DELETE http://localhost:3000/trees/7
Content-Type: application/json

