#  ✅ Operational
#  🛠️ Controller to do

### TREES

### 🛠️ Test deleteTree
DELETE http://localhost:3000/trees/7
Content-Type: application/json

### FOREST

### 🛠️ Test deleteForest
DELETE http://localhost:3000/forests/7
Content-Type: application/json

### USER

### 🛠️ Test deleteUser
DELETE http://localhost:3000/users/7
Content-Type: application/json