#  ✅ Operational
#  🟠 Controller to do

# // AUTHENTICATION
#  ✅ Test Login
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "test"
}

### Test Register 
POST http://localhost:3000/register
Content-Type: application/json

{
  "email": "john3.doe@example.com",
  "password": "test12858/8"
}